package com.marvels.dto.info;

import java.util.Date;

public class XyqbPaymentInfoReturn {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xyqb_payment_info_return.id
     *
     * @mbg.generated Sat Aug 31 17:11:30 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xyqb_payment_info_return.applCde
     *
     * @mbg.generated Sat Aug 31 17:11:30 CST 2019
     */
    private String applCde;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xyqb_payment_info_return.wfSts
     *
     * @mbg.generated Sat Aug 31 17:11:30 CST 2019
     */
    private String wfSts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xyqb_payment_info_return.wfi_out_advice
     *
     * @mbg.generated Sat Aug 31 17:11:30 CST 2019
     */
    private String wfi_out_advice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xyqb_payment_info_return.appl_seq
     *
     * @mbg.generated Sat Aug 31 17:11:30 CST 2019
     */
    private String appl_seq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xyqb_payment_info_return.applSeq
     *
     * @mbg.generated Sat Aug 31 17:11:30 CST 2019
     */
    private String applSeq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xyqb_payment_info_return.formId
     *
     * @mbg.generated Sat Aug 31 17:11:30 CST 2019
     */
    private String formId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xyqb_payment_info_return.ordFormId
     *
     * @mbg.generated Sat Aug 31 17:11:30 CST 2019
     */
    private String ordFormId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xyqb_payment_info_return.cont_no
     *
     * @mbg.generated Sat Aug 31 17:11:30 CST 2019
     */
    private String cont_no;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xyqb_payment_info_return.loan_no
     *
     * @mbg.generated Sat Aug 31 17:11:30 CST 2019
     */
    private String loan_no;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xyqb_payment_info_return.created_date
     *
     * @mbg.generated Sat Aug 31 17:11:30 CST 2019
     */
    private Date created_date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xyqb_payment_info_return.updated_date
     *
     * @mbg.generated Sat Aug 31 17:11:30 CST 2019
     */
    private Date updated_date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xyqb_payment_info_return.created_by
     *
     * @mbg.generated Sat Aug 31 17:11:30 CST 2019
     */
    private String created_by;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xyqb_payment_info_return.updated_by
     *
     * @mbg.generated Sat Aug 31 17:11:30 CST 2019
     */
    private String updated_by;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xyqb_payment_info_return.version
     *
     * @mbg.generated Sat Aug 31 17:11:30 CST 2019
     */
    private Long version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xyqb_payment_info_return.id
     *
     * @return the value of xyqb_payment_info_return.id
     *
     * @mbg.generated Sat Aug 31 17:11:30 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xyqb_payment_info_return.id
     *
     * @param id the value for xyqb_payment_info_return.id
     *
     * @mbg.generated Sat Aug 31 17:11:30 CST 2019
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xyqb_payment_info_return.applCde
     *
     * @return the value of xyqb_payment_info_return.applCde
     *
     * @mbg.generated Sat Aug 31 17:11:30 CST 2019
     */
    public String getApplCde() {
        return applCde;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xyqb_payment_info_return.applCde
     *
     * @param applCde the value for xyqb_payment_info_return.applCde
     *
     * @mbg.generated Sat Aug 31 17:11:30 CST 2019
     */
    public void setApplCde(String applCde) {
        this.applCde = applCde;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xyqb_payment_info_return.wfSts
     *
     * @return the value of xyqb_payment_info_return.wfSts
     *
     * @mbg.generated Sat Aug 31 17:11:30 CST 2019
     */
    public String getWfSts() {
        return wfSts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xyqb_payment_info_return.wfSts
     *
     * @param wfSts the value for xyqb_payment_info_return.wfSts
     *
     * @mbg.generated Sat Aug 31 17:11:30 CST 2019
     */
    public void setWfSts(String wfSts) {
        this.wfSts = wfSts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xyqb_payment_info_return.wfi_out_advice
     *
     * @return the value of xyqb_payment_info_return.wfi_out_advice
     *
     * @mbg.generated Sat Aug 31 17:11:30 CST 2019
     */
    public String getWfi_out_advice() {
        return wfi_out_advice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xyqb_payment_info_return.wfi_out_advice
     *
     * @param wfi_out_advice the value for xyqb_payment_info_return.wfi_out_advice
     *
     * @mbg.generated Sat Aug 31 17:11:30 CST 2019
     */
    public void setWfi_out_advice(String wfi_out_advice) {
        this.wfi_out_advice = wfi_out_advice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xyqb_payment_info_return.appl_seq
     *
     * @return the value of xyqb_payment_info_return.appl_seq
     *
     * @mbg.generated Sat Aug 31 17:11:30 CST 2019
     */
    public String getAppl_seq() {
        return appl_seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xyqb_payment_info_return.appl_seq
     *
     * @param appl_seq the value for xyqb_payment_info_return.appl_seq
     *
     * @mbg.generated Sat Aug 31 17:11:30 CST 2019
     */
    public void setAppl_seq(String appl_seq) {
        this.appl_seq = appl_seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xyqb_payment_info_return.applSeq
     *
     * @return the value of xyqb_payment_info_return.applSeq
     *
     * @mbg.generated Sat Aug 31 17:11:30 CST 2019
     */
    public String getApplSeq() {
        return applSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xyqb_payment_info_return.applSeq
     *
     * @param applSeq the value for xyqb_payment_info_return.applSeq
     *
     * @mbg.generated Sat Aug 31 17:11:30 CST 2019
     */
    public void setApplSeq(String applSeq) {
        this.applSeq = applSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xyqb_payment_info_return.formId
     *
     * @return the value of xyqb_payment_info_return.formId
     *
     * @mbg.generated Sat Aug 31 17:11:30 CST 2019
     */
    public String getFormId() {
        return formId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xyqb_payment_info_return.formId
     *
     * @param formId the value for xyqb_payment_info_return.formId
     *
     * @mbg.generated Sat Aug 31 17:11:30 CST 2019
     */
    public void setFormId(String formId) {
        this.formId = formId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xyqb_payment_info_return.ordFormId
     *
     * @return the value of xyqb_payment_info_return.ordFormId
     *
     * @mbg.generated Sat Aug 31 17:11:30 CST 2019
     */
    public String getOrdFormId() {
        return ordFormId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xyqb_payment_info_return.ordFormId
     *
     * @param ordFormId the value for xyqb_payment_info_return.ordFormId
     *
     * @mbg.generated Sat Aug 31 17:11:30 CST 2019
     */
    public void setOrdFormId(String ordFormId) {
        this.ordFormId = ordFormId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xyqb_payment_info_return.cont_no
     *
     * @return the value of xyqb_payment_info_return.cont_no
     *
     * @mbg.generated Sat Aug 31 17:11:30 CST 2019
     */
    public String getCont_no() {
        return cont_no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xyqb_payment_info_return.cont_no
     *
     * @param cont_no the value for xyqb_payment_info_return.cont_no
     *
     * @mbg.generated Sat Aug 31 17:11:30 CST 2019
     */
    public void setCont_no(String cont_no) {
        this.cont_no = cont_no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xyqb_payment_info_return.loan_no
     *
     * @return the value of xyqb_payment_info_return.loan_no
     *
     * @mbg.generated Sat Aug 31 17:11:30 CST 2019
     */
    public String getLoan_no() {
        return loan_no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xyqb_payment_info_return.loan_no
     *
     * @param loan_no the value for xyqb_payment_info_return.loan_no
     *
     * @mbg.generated Sat Aug 31 17:11:30 CST 2019
     */
    public void setLoan_no(String loan_no) {
        this.loan_no = loan_no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xyqb_payment_info_return.created_date
     *
     * @return the value of xyqb_payment_info_return.created_date
     *
     * @mbg.generated Sat Aug 31 17:11:30 CST 2019
     */
    public Date getCreated_date() {
        return created_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xyqb_payment_info_return.created_date
     *
     * @param created_date the value for xyqb_payment_info_return.created_date
     *
     * @mbg.generated Sat Aug 31 17:11:30 CST 2019
     */
    public void setCreated_date(Date created_date) {
        this.created_date = created_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xyqb_payment_info_return.updated_date
     *
     * @return the value of xyqb_payment_info_return.updated_date
     *
     * @mbg.generated Sat Aug 31 17:11:30 CST 2019
     */
    public Date getUpdated_date() {
        return updated_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xyqb_payment_info_return.updated_date
     *
     * @param updated_date the value for xyqb_payment_info_return.updated_date
     *
     * @mbg.generated Sat Aug 31 17:11:30 CST 2019
     */
    public void setUpdated_date(Date updated_date) {
        this.updated_date = updated_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xyqb_payment_info_return.created_by
     *
     * @return the value of xyqb_payment_info_return.created_by
     *
     * @mbg.generated Sat Aug 31 17:11:30 CST 2019
     */
    public String getCreated_by() {
        return created_by;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xyqb_payment_info_return.created_by
     *
     * @param created_by the value for xyqb_payment_info_return.created_by
     *
     * @mbg.generated Sat Aug 31 17:11:30 CST 2019
     */
    public void setCreated_by(String created_by) {
        this.created_by = created_by;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xyqb_payment_info_return.updated_by
     *
     * @return the value of xyqb_payment_info_return.updated_by
     *
     * @mbg.generated Sat Aug 31 17:11:30 CST 2019
     */
    public String getUpdated_by() {
        return updated_by;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xyqb_payment_info_return.updated_by
     *
     * @param updated_by the value for xyqb_payment_info_return.updated_by
     *
     * @mbg.generated Sat Aug 31 17:11:30 CST 2019
     */
    public void setUpdated_by(String updated_by) {
        this.updated_by = updated_by;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xyqb_payment_info_return.version
     *
     * @return the value of xyqb_payment_info_return.version
     *
     * @mbg.generated Sat Aug 31 17:11:30 CST 2019
     */
    public Long getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xyqb_payment_info_return.version
     *
     * @param version the value for xyqb_payment_info_return.version
     *
     * @mbg.generated Sat Aug 31 17:11:30 CST 2019
     */
    public void setVersion(Long version) {
        this.version = version;
    }
}