/*接口出入参日志*/

DROP TABLE IF EXISTS QJ_ITF_LOG;
CREATE TABLE QJ_ITF_LOG(
	ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
	ITF_CODE VARCHAR(50) NOT NULL COMMENT '接口编码',
	ITF_NAME VARCHAR(100) COMMENT '接口名称',
	ITF_URI VARCHAR(100) COMMENT '接口URI',
	LOCAL_SERIAL VARCHAR(30) COMMENT '本地流水号',
	ASSETS_SERIAL VARCHAR(30) COMMENT '资产方流水号',
	IN_PARAM TEXT COMMENT '入参',
	OUT_PARAM TEXT COMMENT '出参',
	REC_ADD_USR VARCHAR(30) NOT NULL COMMENT '记录作成者',
	REC_ADD_DTT TIMESTAMP NOT NULL DEFAULT NOW() COMMENT '记录作成时间',
	REC_UPD_USR VARCHAR(30) NOT NULL COMMENT '记录更新者',
	REC_UPD_DTT TIMESTAMP NOT NULL DEFAULT NOW() ON UPDATE NOW() COMMENT '记录更新时间',
	PRIMARY KEY (ID)
) ENGINE = InnoDB AUTO_INCREMENT=10000 COMMENT='接口出入参日志' ;