/*短信发送表*/

DROP TABLE IF EXISTS QJ_SEND_SMS;
CREATE TABLE QJ_SEND_SMS(
	ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
	REQUEST_ID VARCHAR(50) NOT NULL COMMENT '请求id',
	CODE VARCHAR(100) COMMENT '返回结果code',
	MESSAGE VARCHAR(100) COMMENT '返回结果描述',
	BIZ_ID VARCHAR(30) COMMENT '返回id',
	PHONE_NUMBERS VARCHAR(30) COMMENT '电话号码',
	TEMPLATE_CODE VARCHAR(30) COMMENT '模板编号',
	TEMPLATE_PARAM VARCHAR(255) COMMENT '替换模板参数',
	CREDIT_BY VARCHAR(30) NOT NULL COMMENT '记录作成者',
	CREATE_TIME TIMESTAMP NOT NULL DEFAULT NOW() COMMENT '记录作成时间',
	UPDATE_BY VARCHAR(30) NOT NULL COMMENT '记录更新者',
	UPDATE_TIME TIMESTAMP NOT NULL DEFAULT NOW() ON UPDATE NOW() COMMENT '记录更新时间',
	PRIMARY KEY (ID)
) ENGINE = InnoDB AUTO_INCREMENT=10000 COMMENT='短信发送表' ;