CREATE TABLE xyqb_credit_apply_info (
  id bigint(10) NOT NULL AUTO_INCREMENT COMMENT 'id',
  req_no varchar(64) DEFAULT NULL COMMENT '创金请求编号',
  ser_no varchar(64) DEFAULT NULL COMMENT '海尔请求编号',
  auto_Flag varchar(30) DEFAULT NULL COMMENT '是否自动提交',
credit_Typ	varchar(10) DEFAULT NULL COMMENT '额度类型',
spe_Seq	varchar(20) DEFAULT NULL COMMENT '专项额度代码',
flag	varchar(5) DEFAULT NULL COMMENT '标示',
user_Id	varchar(30) DEFAULT NULL COMMENT '用户Id',
appl_Seq	varchar(30) DEFAULT NULL COMMENT '额度申请流水号',
appt_Cust_Name	varchar(30) DEFAULT NULL COMMENT '姓名',
appt_Indiv_Sex	varchar(5) DEFAULT NULL COMMENT '性别',
appt_Id_No	varchar(20) DEFAULT NULL COMMENT '身份证号',
indiv_Mobile	varchar(15) DEFAULT NULL COMMENT '手机号',
status	varchar(10) DEFAULT NULL COMMENT '申请状态',
indiv_Edu	varchar(10) DEFAULT NULL COMMENT '最高学历',
indiv_Marital	varchar(10) DEFAULT NULL COMMENT '婚姻状态',
indiv_Dep_No	varchar(10) DEFAULT NULL COMMENT '供养子女数',
appt_Reg_Province	varchar(10) DEFAULT NULL COMMENT '户籍所在省',
appt_Reg_City	varchar(10) DEFAULT NULL COMMENT '户籍所在市',
live_Info	varchar(10) DEFAULT NULL COMMENT '现居住房屋所有权',
live_Province	varchar(10) DEFAULT NULL COMMENT '现居住省',
live_City	varchar(10) DEFAULT NULL COMMENT '现居住市',
live_Area	varchar(10) DEFAULT NULL COMMENT '现居地址区',
live_Addr	varchar(300) DEFAULT NULL COMMENT '现居地址',
local_Resid	varchar(5) DEFAULT NULL COMMENT '户口性质',
live_Year	varchar(6) DEFAULT NULL COMMENT '本地居住年限',
indiv_Emp_Name	varchar(50) DEFAULT NULL COMMENT '单位名称',
indiv_Emp_Typ	varchar(10) DEFAULT NULL COMMENT '行业性质',
indiv_Branch	varchar(10) DEFAULT NULL COMMENT '所在部门',
indiv_Position	varchar(10) DEFAULT NULL COMMENT '职务',
position_Opt	varchar(10) DEFAULT NULL COMMENT '从业性质',
indiv_Emp_Province	varchar(10) DEFAULT NULL COMMENT '单位地址省',
indiv_Emp_City	varchar(10) DEFAULT NULL COMMENT '单位地址市',
indiv_Emp_Area	varchar(10) DEFAULT NULL COMMENT '现单位地址区',
empaddr	varchar(300) DEFAULT NULL COMMENT '现单位地址',
Indiv_Mth_Inc	varchar(10) DEFAULT NULL COMMENT '月均收入',
annual_Earn	varchar(10) DEFAULT NULL COMMENT '税后年收入',
indiv_Emp_Tel	varchar(20) DEFAULT NULL COMMENT '单位电话',
indiv_Work_Yrs	varchar(10) DEFAULT NULL COMMENT '总工龄',
apply_Amt	varchar(30) DEFAULT NULL COMMENT '申请金额',
repay_Appl_Card_No	varchar(30) DEFAULT NULL COMMENT '还款卡号',
repay_Appl_Ac_Nam	varchar(30) DEFAULT NULL COMMENT '账户名',
repay_Acc_Bank_Cde	varchar(30) DEFAULT NULL COMMENT '银行号',
repay_Acc_Bank_Name	varchar(10) DEFAULT NULL COMMENT '开户银行名称',
repay_Ac_Province	varchar(10) DEFAULT NULL COMMENT '开户省',
repay_Ac_City	varchar(10) DEFAULT NULL COMMENT '开户市',
ppty_Live_Opt	varchar(50) DEFAULT NULL COMMENT '房产地址',
ppty_Live_Province	varchar(15) DEFAULT NULL COMMENT '房产地址所在省',
ppty_Live_City	varchar(10) DEFAULT NULL COMMENT '房产地址所在市',
ppty_Live_Area	varchar(10) DEFAULT NULL COMMENT '房产地址所在区',
live_Zip	varchar(10) DEFAULT NULL COMMENT '邮政编码',
ppty_Righ_Name	varchar(30) DEFAULT NULL COMMENT '房屋产权人',
ppty_Amt	varchar(30) DEFAULT NULL COMMENT '购买价格',
ppty_Loan_Ind	varchar(30) DEFAULT NULL COMMENT '是否按揭',
mortgage_Ratio	varchar(30) DEFAULT NULL COMMENT '按揭比例',
ppty_Loan_Year	varchar(30) DEFAULT NULL COMMENT '按揭周期',
mortgage_Partner	varchar(30) DEFAULT NULL COMMENT '按揭参与人',
ppty_Loan_Bank	varchar(30) DEFAULT NULL COMMENT '按揭银行',
operator_Cde	varchar(30) DEFAULT NULL COMMENT '经办人',
operator_Tel	varchar(30) DEFAULT NULL COMMENT '经办人手机号',
coopr_Cde	varchar(30) DEFAULT NULL COMMENT '门店编号',
coopr_Name	varchar(30) DEFAULT NULL COMMENT '门店名称',
expect_Credit	varchar(30) DEFAULT NULL COMMENT '期望额度',
  created_by varchar(50)  DEFAULT 'sys'  COMMENT '创建人',
  created_date datetime NOT NULL   COMMENT '创建时间',
  updated_by varchar(50)   DEFAULT 'sys'  COMMENT '更新人',
  updated_date datetime NOT NULL COMMENT '更新时间',
  ret_msg VARCHAR(500) DEFAULT NULL COMMENT '返回说明:成功，或者拒绝原因',
  PRIMARY KEY (id),
  KEY edc_req_no (req_no) USING BTREE,
  KEY edc_ser_no (ser_no) USING BTREE,
  KEY edc_appt_Id_No (appt_Id_No) USING BTREE,
  KEY edc_indiv_Mobile (indiv_Mobile) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='信用钱包额度申请信息';


CREATE TABLE xyqb_req_info (
  id bigint(10) NOT NULL AUTO_INCREMENT COMMENT 'id',
  req_no varchar(64) DEFAULT NULL COMMENT '创金请求编号',
  ser_no varchar(64) DEFAULT NULL COMMENT '海尔请求编号',
  interface_no varchar(30) DEFAULT NULL COMMENT '接口编号,用的海尔的编号',
  req_json varchar(1000) DEFAULT NULL COMMENT '请求报文',
  res_json	varchar(1200) DEFAULT NULL COMMENT '响应报文',
  created_by varchar(50)  DEFAULT 'sys'  COMMENT '创建人',
  created_date datetime NOT NULL   COMMENT '创建时间',
  updated_by varchar(50)   DEFAULT 'sys'  COMMENT '更新人',
  updated_date datetime NOT NULL COMMENT '更新时间',
  PRIMARY KEY (id),
  KEY edc_req_no (req_no) USING BTREE,
  KEY edc_ser_no (ser_no) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='信用钱包额度申请信息';

CREATE TABLE `xyqb_bind_bank_card` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `cust_name` varchar(50) DEFAULT NULL COMMENT '客户姓名',
  `cert_no` varchar(30) DEFAULT NULL COMMENT '证件证号',
  `card_no` varchar(50) DEFAULT NULL COMMENT '银行卡号',
  `mobile` varchar(20) DEFAULT NULL COMMENT '手机号',
  `acct_province` varchar(50) DEFAULT NULL COMMENT '开户省',
  `acct_city` varchar(50) DEFAULT NULL COMMENT '开户市',
  `acct_area` varchar(50) DEFAULT NULL COMMENT '开户区',
  `accBchCde` varchar(50) DEFAULT NULL COMMENT '开户机构代码',
  `accBch_ame` varchar(50) DEFAULT NULL COMMENT '开户机构名称',
  `sign_status` varchar(20) DEFAULT NULL COMMENT '签约状态 UN_SIGN 未签约 SIGN_SUCCESS 成功 SIGN_EXPIRE 签约过期',
  `code` varchar(10) DEFAULT NULL COMMENT '海尔返回校验编码 00—未认证，保存成功（四要素认证）12—信息认证成功',
  `msg` varchar(50) DEFAULT NULL COMMENT '海尔返回校验信息',
  `error_code` varchar(20) DEFAULT NULL COMMENT '银行返回错误码 00000 成功，其他失败',
  `error_desc` varchar(100) DEFAULT NULL COMMENT '银行错误描述',
  `rtn_code` varchar(20) DEFAULT NULL COMMENT '支付接口调用状态',
  `rtn_msg` varchar(100) DEFAULT NULL COMMENT '支付接口调用信息',
  `cust_no` varchar(50) DEFAULT NULL COMMENT '客户编号',
  `cert_type` varchar(50) DEFAULT NULL COMMENT '证件类型',
  `acct_name` varchar(50) DEFAULT NULL COMMENT '账户名',
  `acct_no` varchar(50) DEFAULT NULL COMMENT '账号',
  `acct_bank_no` varchar(50) DEFAULT NULL COMMENT '银行代码',
  `acct_bank_name` varchar(50) DEFAULT NULL COMMENT '银行名称',
  `belong_store` varchar(50) DEFAULT NULL COMMENT '所属门店',
  `created_by` varchar(50) DEFAULT NULL COMMENT '创建人',
  `created_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` varchar(50) DEFAULT NULL COMMENT '更新用户',
  `updated_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='信用钱包绑卡信息表';

CREATE TABLE `xyqb_file_upload_detail` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `filename` varchar(255) DEFAULT NULL COMMENT '文件名',
  `fileoper` varchar(32) DEFAULT NULL COMMENT '操作类型',
  `file_type` varchar(32) DEFAULT NULL COMMENT '上传类型',
  `file` varchar(128) DEFAULT NULL COMMENT '文件流，文件路径',
  `md5` varchar(255) DEFAULT NULL COMMENT '文件摘要信息',
  `file_uuid` varchar(255) DEFAULT NULL COMMENT '文件唯一标识',
  `creation_date` datetime DEFAULT NULL,
  `appno` varchar(255) DEFAULT NULL COMMENT '流水号',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `xyqb_file_upload` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `channel_no` varchar(255) DEFAULT NULL,
  `appno` varchar(255) DEFAULT NULL COMMENT '流水号',
  `apptime` varchar(32) DEFAULT NULL COMMENT '申请时间（yyyyMMddhhmmss）',
  `appl` varchar(255) DEFAULT NULL COMMENT '申请编号',
  `stage` varchar(32) DEFAULT NULL COMMENT '上送阶段',
  `cert_no` varchar(32) DEFAULT NULL COMMENT '身份证号',
  `creation_date` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `xyqb_common_risk` (
  `id` bigint(11) NOT NULL AUTO_INCREMENT,
  `channelno` varchar(32) DEFAULT NULL COMMENT '渠道编码',
  `applseq` varchar(64) DEFAULT NULL COMMENT '业务编码',
  `type` varchar(255) DEFAULT NULL COMMENT '类型',
  `data` varchar(36) DEFAULT NULL COMMENT '数据',
  `ex_data` varchar(36) DEFAULT NULL COMMENT '扩展数据',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='通用风险接口';

CREATE TABLE `xyqb_common_risk_data` (
  `id` varchar(36) NOT NULL DEFAULT '',
  `nation` varchar(32) DEFAULT NULL COMMENT '名族',
  `idcard_issue` varchar(64) DEFAULT NULL COMMENT '发证机关',
  `idCardNo` varchar(255) DEFAULT NULL COMMENT '身份证号',
  `censusPlace` varchar(128) DEFAULT NULL COMMENT '户籍所在地',
  `idcard_validity_startdate` varchar(32) DEFAULT NULL COMMENT '身份证有效期开始',
  `idcard_validity_enddate` varchar(32) DEFAULT NULL COMMENT '身份证有效期结束',
  `nappGlobalPS` varchar(255) DEFAULT NULL COMMENT '业务发生时点LBS地址',
  `nappProvince` varchar(32) DEFAULT NULL COMMENT '业务发生时点省',
  `nappCity` varchar(32) DEFAULT NULL COMMENT '业务发生时点市',
  `nappArea` varchar(32) DEFAULT NULL COMMENT '业务发生时点区',
  `nappCUID` varchar(64) DEFAULT NULL COMMENT '业务发生时点设备CUID',
  `nappInterPro` varchar(32) DEFAULT NULL COMMENT '业务发生时点IP地址',
  `appEquipment` varchar(255) DEFAULT NULL COMMENT 'imei设备号',
  `wifiAddress` varchar(64) DEFAULT NULL COMMENT 'WIFI-MAC地址',
  `wifiList` varchar(64) DEFAULT NULL COMMENT 'WIFI列表名称',
  `mobimeBrand` varchar(64) DEFAULT NULL COMMENT '手机品牌',
  `phoneModel` varchar(32) DEFAULT NULL,
  `faceScore` varchar(32) DEFAULT NULL COMMENT '人脸识别分数',
  `liveBody` varchar(32) DEFAULT NULL COMMENT '活体识别是否通过',
  `seCredit` varchar(32) DEFAULT NULL COMMENT '芝麻信用分值',
  `isDoFourEle` varchar(32) DEFAULT NULL COMMENT '是否已做四要素验证',
  `isUpFacePic` varchar(32) DEFAULT NULL COMMENT '人脸照片是否上传:0否 1是',
  `isUpIDObv` varchar(32) DEFAULT NULL COMMENT '身份证正面照片是否上传',
  `isUpIDRev` varchar(32) DEFAULT NULL COMMENT '身份证反面照片是否上传',
  `reserved1` varchar(255) DEFAULT NULL,
  `reserved2` varchar(255) DEFAULT NULL,
  `reserved3` varchar(255) DEFAULT NULL,
  `reserved4` varchar(255) DEFAULT NULL,
  `reserved5` varchar(255) DEFAULT NULL,
  `reserved6` varchar(255) DEFAULT NULL,
  `reserved7` varchar(255) DEFAULT NULL,
  `reserved8` varchar(255) DEFAULT NULL,
  `reserved9` varchar(255) DEFAULT NULL,
  `reserved10` varchar(255) DEFAULT NULL,
  `reserved11` varchar(255) DEFAULT NULL,
  `reserved12` varchar(255) DEFAULT NULL,
  `reserved13` varchar(255) DEFAULT NULL,
  `reserved14` varchar(255) DEFAULT NULL,
  `reserved15` varchar(255) DEFAULT NULL,
  `reserved16` varchar(255) DEFAULT NULL,
  `reserved17` varchar(255) DEFAULT NULL,
  `reserved18` varchar(255) DEFAULT NULL,
  `reserved19` varchar(255) DEFAULT NULL,
  `reserved20` varchar(255) DEFAULT NULL,
  `creation_date` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='通用风险接口数据';

CREATE TABLE `xyqb_common_risk_exdata` (
  `id` varchar(36) NOT NULL DEFAULT '',
  `acctName` varchar(32) DEFAULT NULL COMMENT '姓名',
  `appt_id_typ` varchar(32) DEFAULT NULL COMMENT '证件类型',
  `appt_id_no` varchar(32) DEFAULT NULL COMMENT '证件号码',
  `appt_indiv_sex` varchar(32) DEFAULT NULL COMMENT '性别',
  `appt_start_date` varchar(32) DEFAULT NULL COMMENT '出生日期',
  `indiv_marital婚姻状况` varchar(32) DEFAULT NULL COMMENT '婚姻状况',
  `indivEdu` varchar(32) DEFAULT NULL COMMENT '最高学历',
  `mobile` varchar(16) DEFAULT NULL COMMENT '手机号码',
  `appt_reg_province` varchar(32) DEFAULT NULL COMMENT '户籍地址省',
  `appt_reg_city` varchar(32) DEFAULT NULL COMMENT '户籍地址市',
  `live_province` varchar(32) DEFAULT NULL COMMENT '现居住地址省',
  `live_city` varchar(32) DEFAULT NULL COMMENT '现居住地址市',
  `live_area` varchar(32) DEFAULT NULL COMMENT '现居住地址区',
  `live_addr` varchar(255) DEFAULT NULL COMMENT '现居住地址详细地址',
  `idcard_validity_startdate` varchar(32) DEFAULT NULL COMMENT '身份证有效期起始日期',
  `idcard_validity_enddate` varchar(32) DEFAULT NULL COMMENT '身份证有效期终止日期',
  `indivEmpName` varchar(255) DEFAULT NULL COMMENT '现单位名称',
  `indivEmpTyp` varchar(32) DEFAULT NULL COMMENT '单位性质',
  `indivMthInc` varchar(32) DEFAULT NULL COMMENT '月均收入',
  `indivPosition` varchar(32) DEFAULT NULL COMMENT '职务',
  `annualEarn` varchar(32) DEFAULT NULL COMMENT '税后年收入',
  `indiv_emp_province` varchar(32) DEFAULT NULL COMMENT '现单位地址省',
  `indiv_emp_city` varchar(32) DEFAULT NULL COMMENT '现单位地址市',
  `indiv_emp_area` varchar(32) DEFAULT NULL COMMENT '现单位地址区',
  `empaddr` varchar(255) DEFAULT NULL COMMENT '现单位地址详细地址',
  `indivEmpTel` varchar(32) DEFAULT NULL COMMENT '单位电话',
  `relName1` varchar(32) DEFAULT NULL COMMENT '姓名1',
  `relMobile1` varchar(32) DEFAULT NULL COMMENT '手机号2',
  `relRelation1` varchar(255) DEFAULT NULL COMMENT '关系1',
  `relName2` varchar(32) DEFAULT NULL COMMENT '姓名2',
  `relMobile2` varchar(32) DEFAULT NULL COMMENT '手机号2',
  `relRelation2` varchar(32) DEFAULT NULL COMMENT '关系2',
  `liveBody` varchar(32) DEFAULT NULL COMMENT '申请人是否通过活体验证，必填，A+B，0 未通过 1 通过',
  `workplaceSaas` varchar(255) DEFAULT NULL COMMENT '工作单位（SAAS）',
  `workYrs` varchar(32) DEFAULT NULL COMMENT '本单位工作年限',
  `scoreDataSaas` varchar(32) DEFAULT NULL COMMENT '云科谷大数据评分',
  `seCredit` varchar(32) DEFAULT NULL COMMENT '芝麻信息评分',
  `workplaceYB` varchar(255) DEFAULT NULL COMMENT '工作单位（银保监会）',
  `certPracticeNo` varchar(255) DEFAULT NULL COMMENT '执业证编号',
  `certPracticeState` varchar(255) DEFAULT NULL COMMENT '执业证状态',
  `businessScope` varchar(255) DEFAULT NULL COMMENT '业务范围',
  `practiceArea` varchar(255) DEFAULT NULL COMMENT '执业区域',
  `liabilitiesMon` varchar(32) DEFAULT NULL COMMENT '上海资信贷款月负债',
  `portraitComResult` varchar(32) DEFAULT NULL COMMENT '申请人人像比对结果（人像照片VS公安照片）,必填，B',
  `portraitComScore` varchar(32) DEFAULT NULL COMMENT '人像比对分数',
  `isFirstDisburse` varchar(32) DEFAULT NULL COMMENT '是否为首笔支用',
  `thisDisburseDate` varchar(32) DEFAULT NULL COMMENT '本次支用时间',
  `lastDisburseDate` varchar(32) DEFAULT NULL COMMENT '上次支用时间',
  `disburseAmt` varchar(32) DEFAULT NULL COMMENT '支用金额',
  `availAmt` varchar(32) DEFAULT NULL COMMENT '可用额度',
  `typ_desc` varchar(255) DEFAULT NULL COMMENT '贷款品种名称',
  `applyAmt` varchar(32) DEFAULT NULL COMMENT '申请金额(元)',
  `approvalAmt` varchar(32) DEFAULT NULL COMMENT '审批金额（元）',
  `apply_tnr` varchar(32) DEFAULT NULL COMMENT '申请期限',
  `mtdType` varchar(32) DEFAULT NULL COMMENT '还款方式',
  `price_int_rat` varchar(32) DEFAULT NULL COMMENT '定价利率（年）',
  `purpose` varchar(128) DEFAULT NULL COMMENT '贷款用途',
  `creation_date` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='通用风险接口扩展数据';

CREATE TABLE `xyqb_repay_plan_result` (
  `id` varchar(32) NOT NULL DEFAULT '',
  `serno` varchar(64) DEFAULT NULL COMMENT '报文流水号',
  `loanNo` varchar(64) DEFAULT NULL COMMENT '借据号',
  `applSeq` varchar(64) DEFAULT NULL COMMENT '申请流水号',
  `applyDt` varchar(255) DEFAULT NULL COMMENT '申请日期',
  `apprvAmt` decimal(16,2) DEFAULT NULL COMMENT '贷款金额',
  `apprvTnr` varchar(32) DEFAULT NULL COMMENT '总期数',
  `applyTnrTyp` varchar(32) DEFAULT NULL COMMENT '期限类型',
  `cooprCde` varchar(32) DEFAULT NULL COMMENT '门店编号',
  `cooprName` varchar(64) DEFAULT NULL COMMENT '门店名称',
  `channelNo` varchar(32) DEFAULT NULL COMMENT '渠道编号',
  `superCoopr` varchar(32) DEFAULT NULL COMMENT '商户编号',
  `contNo` varchar(64) DEFAULT NULL COMMENT '合同编号',
  `idNo` varchar(32) DEFAULT NULL COMMENT '身份证号',
  `loanMode` varchar(32) DEFAULT NULL COMMENT '是否联合贷款',
  `mtdCde` varchar(32) DEFAULT NULL COMMENT '还款方式',
  `mtdDesc` varchar(255) DEFAULT NULL COMMENT '还款方式描述',
  `typGrp` varchar(32) DEFAULT NULL COMMENT '贷款类型',
  `loanTyp` varchar(64) DEFAULT NULL COMMENT '贷款产品',
  `nextDueDt` varchar(32) DEFAULT NULL COMMENT '下一次还款日',
  `lastDueDt` varchar(32) DEFAULT NULL COMMENT '最后还款日',
  `loanOdInd` varchar(32) DEFAULT NULL COMMENT '贷款状态',
  `creation_date` datetime DEFAULT NULL,
  `update_date` datetime DEFAULT NULL,
  `created_by` varchar(64) DEFAULT NULL,
  `updated_by` varchar(64) DEFAULT NULL,
  `version` bigint(20) DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='还款计划查询';

CREATE TABLE `xyqb_repay_plan_lmpmshd` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `psPerdNo` varchar(32) DEFAULT NULL COMMENT '期号',
  `psDueDt` varchar(32) DEFAULT NULL COMMENT '到期日',
  `psPrcpAmt` decimal(16,2) DEFAULT NULL COMMENT '本金',
  `psNormInt` decimal(16,2) DEFAULT NULL COMMENT '正常利息',
  `psOdIntAmt` decimal(16,2) DEFAULT NULL COMMENT '逾期利息',
  `psCommOdInt` decimal(16,2) DEFAULT NULL COMMENT '复利',
  `psFeeAmt` decimal(16,2) DEFAULT NULL COMMENT '费用金额',
  `setlPrcp` decimal(16,2) DEFAULT NULL COMMENT '已还本金',
  `setlNormInt` decimal(16,2) DEFAULT NULL COMMENT '已还利息',
  `setlOdIntAmt` decimal(16,2) DEFAULT NULL COMMENT '已还逾期利息',
  `setlCommOdInt` decimal(16,2) DEFAULT NULL COMMENT '已还复利',
  `setlFeeAmt` decimal(16,2) DEFAULT NULL COMMENT '已还费用金额',
  `setlInd` varchar(4) DEFAULT NULL COMMENT '结清标志Y已结清N未结清',
  `psOdInd` varchar(4) DEFAULT NULL COMMENT '逾期标志当期本金、利息、罚息、复利、费用如果有未结清的，则该标志为''Y''',
  `lastSetlDt` varchar(32) DEFAULT NULL COMMENT '实际还款日',
  `psIntRate` decimal(16,9) DEFAULT NULL COMMENT '利率',
  `psOdIntRate` decimal(16,9) DEFAULT NULL COMMENT '罚息利率',
  `psRemPrcp` decimal(16,2) DEFAULT NULL COMMENT '剩余本金',
  `acctFeeAmt` decimal(16,2) DEFAULT NULL COMMENT '账号管理费',
  `setlAcctFeeAmt` decimal(16,2) DEFAULT NULL COMMENT '已还账号管理费',
  `penalFeeAmt` decimal(16,2) DEFAULT NULL COMMENT '违约金',
  `setlPenalFeeAmt` decimal(16,2) DEFAULT NULL COMMENT '已还违约金',
  `lateFeeAmt` decimal(16,2) DEFAULT NULL COMMENT '滞纳金',
  `setlLateFeeAmt` decimal(16,2) DEFAULT NULL COMMENT '已还滞纳金',
  `psInstmAmt` decimal(16,2) DEFAULT NULL COMMENT '期供金额',
  `advanceFeeAmt` decimal(16,2) DEFAULT NULL COMMENT '提前还款手续费',
  `setlAdvanceFeeAmt` decimal(16,2) DEFAULT NULL COMMENT '已还提前还款手续费',
  `psWvNmInt` decimal(16,2) DEFAULT NULL COMMENT '减免正常利息',
  `psWvOdInt` decimal(16,2) DEFAULT NULL COMMENT '减免逾期利息',
  `psWvCommInt` decimal(16,2) DEFAULT NULL COMMENT '减免复利',
  `plan_result_id` varchar(32) DEFAULT NULL COMMENT '对应的上级result的主键id',
  `creation_date` datetime DEFAULT NULL,
  `update_date` datetime DEFAULT NULL,
  `created_by` varchar(64) DEFAULT NULL,
  `updated_by` varchar(64) DEFAULT NULL,
  `version` bigint(20) DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='还款查询结果列表子集数据';


##LP20002接口sql
##现金贷支用信息主表
CREATE TABLE `xyqb_payment_info_main` (
  `id` varchar(32) NOT NULL DEFAULT '主键',
  `id_typ` varchar(64) DEFAULT '20' COMMENT '默认送‘20’(身份证)',
  `id_no` varchar(64) DEFAULT NULL COMMENT '身份号码需满足身份证生成规则',
  `cust_name` varchar(64) DEFAULT NULL COMMENT '申请人姓名',
  `coopr_name` varchar(64) DEFAULT NULL COMMENT '消金业务负责人确认提供',
  `cont_zone` varchar(32) DEFAULT NULL COMMENT '门店联系电话区号',
  `cont_tel` varchar(32) DEFAULT NULL COMMENT '门店联系电话',
  `cont_sub` varchar(32) DEFAULT NULL COMMENT '门店联系电话分机',
  `typ_grp` varchar(32) DEFAULT NULL COMMENT '贷款类型',
  `prom_cde` varchar(64) DEFAULT NULL COMMENT '营销专案代码',
  `prom_desc` varchar(32) DEFAULT NULL COMMENT '营销专案名称',
  `typ_seq` decimal(16,2) DEFAULT NULL COMMENT '贷款品种流水号',
  `typ_cde` varchar(64) DEFAULT NULL COMMENT '贷款品种代码',
  `typ_desc` varchar(32) DEFAULT NULL COMMENT '贷款品种名称',
  `apply_dt` varchar(32) DEFAULT NULL COMMENT '申请日期',
  `crt_dt` varchar(32) DEFAULT NULL COMMENT '登记日期',
  `crt_usr` varchar(32) DEFAULT NULL COMMENT '登记人代码',
  `indiv_mobile` varchar(32) DEFAULT NULL COMMENT '移动电话',
  `pro_pur_amt` decimal(16,2) DEFAULT NULL COMMENT '购买总额',
  `fst_pct` decimal(16,2) DEFAULT NULL COMMENT '首付比例',
  `fst_pay` decimal(16,2) DEFAULT NULL COMMENT '首付金额',
  `apply_amt` decimal(16,2) DEFAULT NULL COMMENT '申请金额（元）',
  `apply_tnr` varchar(32) DEFAULT NULL COMMENT '申请期限',
  `apply_tnr_typ` varchar(32) DEFAULT NULL COMMENT '期限类型',
  `purpose` varchar(32) DEFAULT NULL COMMENT '贷款用途',
  `other_purpose` varchar(32) DEFAULT NULL COMMENT '贷款其他用途',
  `month_repay` decimal(16,2) DEFAULT NULL COMMENT '可接受月还款（元）',
  `oper_goods_typ` varchar(32) DEFAULT NULL COMMENT '采购产品种类',
  `mtd_cde` varchar(32) DEFAULT NULL COMMENT '还款方式',
  `loan_freq` varchar(32) DEFAULT NULL COMMENT '还款间隔',
  `mtd_mode` varchar(32) DEFAULT NULL COMMENT '利率模式',
  `repc_opt` varchar(32) DEFAULT NULL COMMENT '利率调整方式',
  `price_int_rat` decimal(16,2) DEFAULT NULL COMMENT '定价利率（年）',
  `due_day_opt` varchar(32) DEFAULT NULL COMMENT '每期还款日',
  `due_day` varchar(32) DEFAULT NULL COMMENT '还款日',
  `doc_channel` varchar(32) DEFAULT NULL COMMENT '进件通路',
  `appl_ac_typ` varchar(32) DEFAULT NULL COMMENT '账号类型',
  `appl_ac_nam` varchar(32) DEFAULT NULL COMMENT '账号户名',
  `appl_card_no` varchar(32) DEFAULT NULL COMMENT '卡号',
  `acc_bank_cde` varchar(32) DEFAULT NULL COMMENT '开户银行代码',
  `acc_bank_name` varchar(32) DEFAULT NULL COMMENT '开户银行名',
  `ac_province` varchar(32) DEFAULT NULL COMMENT '（放款账户）账户所在省',
  `ac_city` varchar(32) DEFAULT NULL COMMENT '（放款账户）账户所在市',
  `appl_ac_bch` varchar(32) DEFAULT NULL COMMENT '（放款账户）开户机构（12位联行号）',
  `repay_appl_ac_nam` varchar(32) DEFAULT NULL COMMENT '还款账号户名',
  `repay_appl_card_no` varchar(32) DEFAULT NULL COMMENT '还款卡号',
  `repay_acc_bank_cde` varchar(32) DEFAULT NULL COMMENT '开户银行代码',
  `repay_acc_bank_name` varchar(32) DEFAULT NULL COMMENT '开户银行名',
  `repay_ac_province` varchar(32) DEFAULT NULL COMMENT '账户所在省',
  `repay_ac_city` varchar(32) DEFAULT NULL COMMENT '账户所在市',
  `saler_cde` varchar(32) DEFAULT NULL COMMENT '销售代表代码',
  `saler_name` varchar(32) DEFAULT NULL COMMENT '销售代表姓名',
  `saler_mobile` varchar(32) DEFAULT NULL COMMENT '销售代表电话',
  `app_in_advice` varchar(32) DEFAULT NULL COMMENT '备注',
  `operator_name` varchar(32) DEFAULT NULL COMMENT '客户经理名称',
  `operator_cde` varchar(32) DEFAULT NULL COMMENT '客户经理代码',
  `operator_tel` varchar(32) DEFAULT NULL COMMENT '客户经理联系电话',
  `crd_flag` varchar(32) DEFAULT NULL COMMENT '是否需要额度申请加支用',
  `creditType` varchar(32) DEFAULT NULL COMMENT '支用类型',
  `ppty_live_opt` varchar(32) DEFAULT NULL COMMENT '房产地址选项',
  `ppty_live_province` varchar(32) DEFAULT NULL COMMENT '省',
  `ppty_live_city` varchar(32) DEFAULT NULL COMMENT '市',
  `ppty_live_area` varchar(32) DEFAULT NULL COMMENT '区',
  `ppty_live_addr` varchar(32) DEFAULT NULL COMMENT '详细地址',
  `ppty_righ_name` varchar(32) DEFAULT NULL COMMENT '房产产权人',
  `ppty_amt` decimal(16,2) DEFAULT NULL COMMENT '购买价格',
  `ppty_loan_ind` varchar(32) DEFAULT NULL COMMENT '是否按揭',
  `ppty_loan_amt` decimal(16,2) DEFAULT NULL COMMENT '按揭金额',
  `ppty_loan_year` decimal(16,2) DEFAULT NULL COMMENT '按揭周期（年）',
  `ppty_loan_bank` varchar(32) DEFAULT NULL COMMENT '按揭银行',
  `asset_kind` varchar(32) DEFAULT NULL COMMENT '资产性质',
  `asset_typ` varchar(32) DEFAULT NULL COMMENT '资产类型',
  `asset_amt` decimal(16,2) DEFAULT NULL COMMENT '金额',
  `asset_mth_amt` decimal(16,2) DEFAULT NULL COMMENT '月还款额',
  `asset_re_amt` decimal(16,2) DEFAULT NULL COMMENT '贷款余额',
  `grt_type` varchar(32) DEFAULT NULL COMMENT '担保方式',
  `grt_coopr_cde` varchar(32) DEFAULT NULL COMMENT '商户/合同机构代码',
  `grt_coopr_name` varchar(32) DEFAULT NULL COMMENT '商户/合作机构名称',
  `grt_corporate_name` varchar(32) DEFAULT NULL COMMENT '法人',
  `grt_corporate_tel` varchar(32) DEFAULT NULL COMMENT '法人电话',
  `grt_coopr_contact_email` varchar(32) DEFAULT NULL COMMENT '法人邮箱',
  `grt_ind_officer` varchar(32) DEFAULT NULL COMMENT '工贸客户经理',
  `grt_coopr_tnr` varchar(32) DEFAULT NULL COMMENT '与担保人合作年',
  `created_date` datetime DEFAULT NULL,
  `updated_date` datetime DEFAULT NULL,
  `created_by` varchar(64) DEFAULT NULL,
  `updated_by` varchar(64) DEFAULT NULL,
  `version` bigint(20) DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='现金贷支用信息主表';

##现金贷支用信息物品表
CREATE TABLE `xyqb_payment_info_good` (
  `id` varchar(32) NOT NULL DEFAULT '主键',
  `goods_brand` varchar(64) DEFAULT NULL COMMENT '产品/服务品牌',
  `goods_kind` varchar(64) DEFAULT NULL COMMENT '产品/服务类型',
  `goods_name` varchar(64) DEFAULT NULL COMMENT '商品名称',
  `goods_model` varchar(255) DEFAULT NULL COMMENT '商品型号',
  `goods_num` decimal(16) DEFAULT NULL COMMENT '商品数量',
  `goods_price` decimal(16,2) DEFAULT NULL COMMENT '商品单价（元）',
  `payment_info_main_id` varchar(32) NOT NULL DEFAULT '现金贷支用信息主表id',
  `created_date` datetime DEFAULT NULL,
  `updated_date` datetime DEFAULT NULL,
  `created_by` varchar(64) DEFAULT NULL,
  `updated_by` varchar(64) DEFAULT NULL,
  `version` bigint(20) DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='现金贷支用信息物品表';

##现金贷支用信息--申请人亲属信息表
CREATE TABLE `xyqb_payment_info_appt` (
  `id` varchar(32) NOT NULL DEFAULT '主键',
  `appt_typ` varchar(64) DEFAULT NULL COMMENT '申请人类型',
  `appt_relation` varchar(64) DEFAULT NULL COMMENT '与主申请人的关系',
  `appt_id_typ` varchar(64) DEFAULT NULL COMMENT '证件类型',
  `appt_id_typ_oth` varchar(255) DEFAULT NULL COMMENT '证件类型其他备注',
  `appt_id_no` decimal(16,2) DEFAULT NULL COMMENT '证件号码',
  `appt_cust_name` varchar(32) DEFAULT NULL COMMENT '姓名',
  `appt_indiv_sex` varchar(32) DEFAULT NULL COMMENT '性别',
  `appt_start_date` varchar(32) DEFAULT NULL COMMENT '出生日期',
  `indiv_marital` varchar(32) DEFAULT NULL COMMENT '婚姻状况',
  `indiv_edu` varchar(32) DEFAULT NULL COMMENT '最高学历',
  `appt_reg_province` varchar(32) DEFAULT NULL COMMENT '户籍地址省',
  `appt_reg_city` varchar(32) DEFAULT NULL COMMENT '户籍地址市',
  `live_info` varchar(32) DEFAULT NULL COMMENT '现住房情况',
  `live_province` varchar(32) DEFAULT NULL COMMENT '现住房省',
  `live_city` varchar(32) DEFAULT NULL COMMENT '现住房市',
  `live_area` varchar(32) DEFAULT NULL COMMENT '现住房区',
  `live_addr` varchar(32) DEFAULT NULL COMMENT '现住房地址',
  `live_zip` varchar(32) DEFAULT NULL COMMENT '现住房邮编',
  `live_mj` decimal(16,2) DEFAULT NULL COMMENT '现住房面积',
  `ppty_live` varchar(32) DEFAULT NULL COMMENT '自有房产地址',
  `ppty_province` varchar(32) DEFAULT NULL COMMENT '自有房产省',
  `ppty_city` varchar(32) DEFAULT NULL COMMENT '自有房产市',
  `ppty_area` varchar(32) DEFAULT NULL COMMENT '自有房产区',
  `ppty_addr` varchar(32) DEFAULT NULL COMMENT '自有房产详细地址',
  `ppty_zip` varchar(32) DEFAULT NULL COMMENT '自有房产邮编',
  `ppty_mj` decimal(16,2) DEFAULT NULL COMMENT '自有房面积',
  `indiv_mobile` varchar(32) DEFAULT NULL COMMENT '移动电话',
  `indiv_fmly_zone` varchar(32) DEFAULT NULL COMMENT '家庭电话区号',
  `indiv_fmly_tel` varchar(32) DEFAULT NULL COMMENT '家庭电话',
  `local_resid` varchar(32) DEFAULT NULL COMMENT '户口性质',
  `indiv_email` varchar(32) DEFAULT NULL COMMENT '电子邮箱',
  `live_year` decimal(16,2) DEFAULT NULL COMMENT '本地已居住时间（年）',
  `indiv_dep_no` decimal(16) DEFAULT NULL COMMENT '供养人数（子女）',
  `annual_earn` decimal(16,2) DEFAULT NULL COMMENT '年收入（税后）',
  `household_own_rel` varchar(32) DEFAULT NULL COMMENT '户主与本人关系',
  `max_crdt_card` decimal(16,2) DEFAULT NULL COMMENT '信用卡最高额度',
  `iss_bank` decimal(16,2) DEFAULT NULL COMMENT '本人持有几家银行的信用卡',
  `position_opt` varchar(32) DEFAULT NULL COMMENT '工作性质',
  `indiv_mth_inc` decimal(16,2) DEFAULT NULL COMMENT '月均收入',
  `mail_opt` varchar(32) DEFAULT NULL COMMENT '送货地址选项',
  `study_mth` varchar(32) DEFAULT NULL COMMENT '学习方式',
  `studying_deg` varchar(32) DEFAULT NULL COMMENT '在读学历',
  `school_name` varchar(32) DEFAULT NULL COMMENT '学校名称',
  `study_major` varchar(32) DEFAULT NULL COMMENT '专业',
  `school_kind` varchar(32) DEFAULT NULL COMMENT '学校性质',
  `school_leng` varchar(32) DEFAULT NULL COMMENT '学制',
  `geade` varchar(32) DEFAULT NULL COMMENT '年级',
  `emp_reg_name` varchar(32) DEFAULT NULL COMMENT '年级名称',
  `emp_reg_dt` varchar(32) DEFAULT NULL COMMENT '成立日期',
  `manage_addr` varchar(32) DEFAULT NULL COMMENT '经营地址',
  `manage_province` varchar(32) DEFAULT NULL COMMENT '经营地址省',
  `manage_city` varchar(32) DEFAULT NULL COMMENT '经营地址市',
  `manage_area` varchar(32) DEFAULT NULL COMMENT '经营地址区',
  `emp_reg_rel_tel` varchar(32) DEFAULT NULL COMMENT '企业联系电话',
  `emp_reg_add_zip` varchar(32) DEFAULT NULL COMMENT '企业地址邮编',
  `emp_reg_num` varchar(32) DEFAULT NULL COMMENT '企业注册号',
  `inc_cde` varchar(32) DEFAULT NULL COMMENT '所属工贸',
  `indiv_opt` varchar(32) DEFAULT NULL COMMENT '申请人身份',
  `share_hold_pct` varchar(32) DEFAULT NULL COMMENT '持股比例',
  `manage_typ` varchar(32) DEFAULT NULL COMMENT '经营实体类型',
  `manage_main_biz` varchar(32) DEFAULT NULL COMMENT '主营业务',
  `mth_turnover` varchar(32) DEFAULT NULL COMMENT '月均营业额（万元）',
  `manage_no` varchar(32) DEFAULT NULL COMMENT '营业执照号',
  `pur_sale_cont_no` varchar(32) DEFAULT NULL COMMENT '购销合同编号',
  `indiv_emp_name` varchar(32) DEFAULT NULL COMMENT '现单位名称',
  `indiv_branch` varchar(32) DEFAULT NULL COMMENT '所在部门',
  `indiv_emp_typ` varchar(32) DEFAULT NULL COMMENT '现单位性质',
  `indiv_emp_yrs` varchar(32) DEFAULT NULL COMMENT '现单位工龄',
  `indiv_emp_province` varchar(32) DEFAULT NULL COMMENT '现单位地址省',
  `indiv_emp_city` varchar(32) DEFAULT NULL COMMENT '现单位地址市',
  `indiv_emp_area` varchar(32) DEFAULT NULL COMMENT '现单位地址区',
  `empaddr` varchar(32) DEFAULT NULL COMMENT '现单位地址',
  `indiv_emp_zip` varchar(32) DEFAULT NULL COMMENT '现单位邮编',
  `indiv_emp_zone` varchar(32) DEFAULT NULL COMMENT '办公电话区号',
  `indiv_emp_tel` varchar(32) DEFAULT NULL COMMENT '办公电话',
  `indiv_emp_tel_sub` varchar(32) DEFAULT NULL COMMENT '办公电话分机',
  `indiv_emp_hr_zone` varchar(32) DEFAULT NULL COMMENT '办公电话2区号',
  `indiv_emp_hr_phone` varchar(32) DEFAULT NULL COMMENT '办公电话2',
  `indiv_emp_hr_sub` varchar(32) DEFAULT NULL COMMENT '办公电话2分机',
  `indiv_position` varchar(32) DEFAULT NULL COMMENT '职务',
  `indiv_work_yrs` varchar(32) DEFAULT NULL COMMENT '总工龄',
  `spouse_name` varchar(32) DEFAULT NULL COMMENT '配偶姓名',
  `spouse_id_typ` varchar(32) DEFAULT NULL COMMENT '配偶证件类型',
  `spouse_id_no` varchar(32) DEFAULT NULL COMMENT '配偶证件号码',
  `spouse_emp` varchar(32) DEFAULT NULL COMMENT '配偶工作单位名称',
  `spouse_mobile` varchar(32) DEFAULT NULL COMMENT '配偶手机号',
  `spouse_branch` varchar(32) DEFAULT NULL COMMENT '配偶工作单位所在部门',
  `spouse_emp_zone` varchar(32) DEFAULT NULL COMMENT '配偶办公电话区号',
  `spouse_emp_tel` varchar(32) DEFAULT NULL COMMENT '配偶办公电话',
  `spouse_emp_tel_sub` varchar(32) DEFAULT NULL COMMENT '配偶办公电话分机',
  `spouse_emp_province` varchar(32) DEFAULT NULL COMMENT '配偶单位地址省',
  `spouse_emp_city` varchar(32) DEFAULT NULL COMMENT '配偶单位地址市',
  `spouse_emp_area` varchar(32) DEFAULT NULL COMMENT '配偶单位地址区',
  `spouse_emp_addr` varchar(32) DEFAULT NULL COMMENT '配偶单位地址',
  `sp_mth_inc` decimal(16,2) DEFAULT NULL COMMENT '月均收入',
  `spouse_pay_ind` varchar(32) DEFAULT NULL COMMENT '是否为共同还款人',
  `payment_info_main_id` varchar(32) NOT NULL DEFAULT '现金贷支用信息主表id',
  `created_date` datetime DEFAULT NULL,
  `updated_date` datetime DEFAULT NULL,
  `created_by` varchar(64) DEFAULT NULL,
  `updated_by` varchar(64) DEFAULT NULL,
  `version` bigint(20) DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='现金贷支用信息--申请人亲属信息表';


##现金贷支用信息--申请人亲属信息附表
CREATE TABLE `xyqb_payment_info_appt_rel` (
  `id` varchar(32) NOT NULL DEFAULT '主键',
  `rel_name` varchar(64) DEFAULT NULL COMMENT '联系人姓名',
  `rel_id_typ` varchar(64) DEFAULT NULL COMMENT '证件类型',
  `rel_id_no` varchar(64) DEFAULT NULL COMMENT '证件号码',
  `rel_relation` varchar(64) DEFAULT NULL COMMENT '联系人与申请人关系',
  `rel_addr` varchar(64) DEFAULT NULL COMMENT '联系地址',
  `rel_mobile` varchar(64) DEFAULT NULL COMMENT '联系电话',
  `rel_emp_name` varchar(64) NOT NULL DEFAULT '单位名称',
  `payment_info_appt_id` varchar(32) NOT NULL DEFAULT '现金贷支用信息--申请人亲属信息表id',
  `created_date` datetime DEFAULT NULL,
  `updated_date` datetime DEFAULT NULL,
  `created_by` varchar(64) DEFAULT NULL,
  `updated_by` varchar(64) DEFAULT NULL,
  `version` bigint(20) DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='现金贷支用信息--申请人亲属信息附表';


####现金贷支用信息接口返回表


####现金贷支用信息接口返回表
CREATE TABLE `xyqb_payment_info_return` (
  `id` varchar(32) NOT NULL DEFAULT '主键',
  `applCde` varchar(64) DEFAULT NULL COMMENT '申请编号',
  `wfSts` varchar(64) DEFAULT NULL COMMENT '审批状态（外部状态）',
  `wfi_out_advice` varchar(64) DEFAULT NULL COMMENT '审批意见（外部意见）',
  `appl_seq` varchar(64) DEFAULT NULL COMMENT '申请流水号',
  `applSeq` varchar(64) DEFAULT NULL COMMENT '申请流水号',
  `formId` varchar(16) DEFAULT NULL COMMENT '订单表主键',
  `ordFormId` varchar(32) NULL DEFAULT NULL COMMENT '订单表主键',
  `cont_no` varchar(32) NOT NULL COMMENT '合同编号',
  `loan_no` varchar(32) NOT NULL COMMENT '借据号',
  `created_date` datetime DEFAULT NULL,
  `updated_date` datetime DEFAULT NULL,
  `created_by` varchar(64) DEFAULT NULL,
  `updated_by` varchar(64) DEFAULT NULL,
  `version` bigint(20) DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='现金贷支用信息--申请人亲属信息附表'

##LP30001
##主动还款试算入参表
CREATE TABLE `xyqb_initiative_repayment_info` (
  `id` varchar(32) NOT NULL DEFAULT '主键',
  `loanNo` varchar(64) DEFAULT NULL COMMENT '借据号',
  `setlMode` varchar(64) DEFAULT NULL COMMENT '还款类型:FS（全部还款）NM（归还欠款）NF (指定期数还款,不适用于整笔逾期数据和非应计数据)ER：提前部分还款',
  `actvPayInd` varchar(64) DEFAULT NULL COMMENT '提前还款金额类型',
  `actvPayAmt` varchar(255) DEFAULT NULL COMMENT '主动还款金额',
  `actvPrcp` decimal(16) DEFAULT NULL COMMENT '主动还款本金',
  `paymInd` decimal(16,2) DEFAULT NULL COMMENT '本次还款是否已到账',
  `expRecCde` varchar(32) NOT NULL DEFAULT '途径',
  `coupNo` varchar(32) NOT NULL DEFAULT '优惠券号',
  `setlTyp` varchar(32) NOT NULL DEFAULT '固定传值，传NM',
  `relPerdCnt` varchar(32) NOT NULL DEFAULT '缩期期数',
  `setlValDt` varchar(32) NOT NULL DEFAULT '指定归还时间',
  `created_date` datetime DEFAULT NULL,
  `updated_date` datetime DEFAULT NULL,
  `created_by` varchar(64) DEFAULT NULL,
  `updated_by` varchar(64) DEFAULT NULL,
  `version` bigint(20) DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='主动还款试算入参表';

##主动还款试算返回表
CREATE TABLE `xyqb_initiative_repayment_resp` (
  `id` varchar(32) NOT NULL DEFAULT '主键',
  `loanNo` varchar(64) DEFAULT NULL COMMENT '借据号',
  `relPerdCnt` varchar(64) DEFAULT NULL COMMENT '相对缩期期数',
  `prcpAmt` varchar(64) DEFAULT NULL COMMENT '应归还逾期本金',
  `normInt` varchar(64) DEFAULT NULL COMMENT '应归还正常利息',
  `odInt` varchar(16) DEFAULT NULL COMMENT '应归还逾期利息',
  `commInt` varchar(64) DEFAULT NULL COMMENT '应归还复利',
  `actvPrcp` varchar(32) NOT NULL DEFAULT '提前还款本金',
  `earlyRepayAmt` varchar(32) NOT NULL DEFAULT '提前还款手续费',
  `repayAmt` varchar(32) NOT NULL DEFAULT '应还手续费',
  `penaltyAmt` varchar(32) NOT NULL DEFAULT '违约金',
  `lateAmt` varchar(32) NOT NULL DEFAULT '滞纳金',
  `actvNormInt` varchar(32) NOT NULL DEFAULT '主动还款利息',
  `repayAmts` varchar(32) NOT NULL DEFAULT '应还总手续费',
  `feeAmt` varchar(32) NOT NULL DEFAULT '应还总费用',
  `coupUseAmt` varchar(32) NOT NULL DEFAULT '减免金额',
  `coupNo` varchar(32) NOT NULL DEFAULT '优惠券号',
  `RField1` varchar(32) NOT NULL DEFAULT '保留字段1',
  `Rfield2` varchar(32) NOT NULL DEFAULT '保留字段2',
  `Rfield3` varchar(32) NOT NULL DEFAULT '保留字段3',
  `Rfield4` varchar(32) NOT NULL DEFAULT '保留字段4',
  `Rfield5` varchar(32) NOT NULL DEFAULT '保留字段5',
  `created_date` datetime DEFAULT NULL,
  `updated_date` datetime DEFAULT NULL,
  `created_by` varchar(64) DEFAULT NULL,
  `updated_by` varchar(64) DEFAULT NULL,
  `version` bigint(20) DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='主动还款试算返回表';

##LP30002
##主主动还款提交入参表
CREATE TABLE `xyqb_initiative_repaysubmit_info` (
  `id` varchar(32)  NOT NULL COMMENT '主键',
  `applSeq` varchar(64) DEFAULT NULL COMMENT '贷款申请流水号',
  `loanNo` varchar(64) DEFAULT NULL COMMENT '借据号',
  `setlTyp` varchar(64) DEFAULT NULL COMMENT '还款方式',
  `setlMode` varchar(64) DEFAULT NULL COMMENT '还款类型',
  `repayAmt` decimal(16,2) DEFAULT NULL COMMENT '还款总金额',
  `psPerdNo` varchar(64) DEFAULT NULL COMMENT '还款期',
  `actvPayInd` varchar(64) DEFAULT NULL COMMENT '提前还款类型',
  `actvPrcp` varchar(32)  DEFAULT NULL COMMENT '提前还款本金',
  `setlValDt` varchar(32)  DEFAULT NULL COMMENT '指定的提前指定归还时间',
  `isUseAcCardNo` varchar(32)  DEFAULT NULL COMMENT '是否使用参数acCardNo指定的`还款卡进行还款',
  `acCardNo` varchar(32)  DEFAULT NULL COMMENT '还款卡号',
  `acProvince` varchar(32)  DEFAULT NULL COMMENT '开户省',
  `acCity` varchar(32)  DEFAULT NULL COMMENT '开户市',
  `acName` varchar(32)  DEFAULT NULL COMMENT '还款卡开户名',
  `acBch` varchar(32)  DEFAULT NULL COMMENT '联行号',
  `paymInd` varchar(32)  DEFAULT NULL COMMENT '本次还款是否已到账',
  `expRecCde` varchar(32)  DEFAULT NULL COMMENT '途径',
  `isNeedPayNo` varchar(32)  DEFAULT NULL COMMENT '是否需要支付流水号',
  `useCoup` varchar(32)  DEFAULT NULL COMMENT '是否使用优惠券',
  `coupNo` varchar(32)  DEFAULT NULL COMMENT '优惠券代码',
  `coupUseAmt` decimal(16,2) DEFAULT NULL COMMENT '优惠券减免金额',
  `custNo` varchar(32)  DEFAULT NULL COMMENT '客户编号',
  `excessMoney` varchar(32)  DEFAULT NULL COMMENT '溢缴款',
  `created_date` datetime DEFAULT NULL,
  `updated_date` datetime DEFAULT NULL,
  `created_by` varchar(64) DEFAULT NULL,
  `updated_by` varchar(64) DEFAULT NULL,
  `version` bigint(20) DEFAULT NULL COMMENT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='主动还款试算入参表';

##主动还款提交返回表
CREATE TABLE `xyqb_initiative_repaysubmit_resp` (
  `id` varchar(32)  NOT NULL COMMENT '主键',
  `loanNo` varchar(64) DEFAULT NULL COMMENT '借据号',
  `applSeq` varchar(64) DEFAULT NULL COMMENT '贷款申请流水号',
  `repaySeq` varchar(64) DEFAULT NULL COMMENT '还款主键',
  `setlSts` varchar(64) DEFAULT NULL COMMENT '还款状态',
  `failReason` varchar(16) DEFAULT NULL COMMENT '还款失败原因',
  `excessCode` varchar(64) DEFAULT NULL COMMENT '溢缴款标志位',
  `payNo` varchar(32)  DEFAULT NULL COMMENT '支付流水号',
  `created_date` datetime DEFAULT NULL,
  `updated_date` datetime DEFAULT NULL,
  `created_by` varchar(64) DEFAULT NULL,
  `updated_by` varchar(64) DEFAULT NULL,
  `version` bigint(20) DEFAULT NULL COMMENT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='主动还款试算返回表';

##LP30003
##主动还款进度查询入参表
CREATE TABLE `xyqb_initiative_repaysrate_info` (
  `id` varchar(32)  NOT NULL COMMENT '主键',
  `sortNo` varchar(64) DEFAULT NULL COMMENT '请求标志位',
  `serno` varchar(64) DEFAULT NULL COMMENT '历史请求序列号',
  `custNo` varchar(64) DEFAULT NULL COMMENT '客户编号',
  `loanNo` varchar(64) DEFAULT NULL COMMENT '借据号',
  `applSeq` decimal(16,2) DEFAULT NULL COMMENT '贷款申请流水号',
  `setlMode` varchar(64) DEFAULT NULL COMMENT '还款类型',
  `setlTyp` varchar(64) DEFAULT NULL COMMENT '还款方式',
  `setlSts` varchar(32)  DEFAULT NULL COMMENT '还款状态',
  `repaySeq` varchar(32)  DEFAULT NULL COMMENT '还款主键',
  `isNeedPayNo` varchar(32)  DEFAULT NULL COMMENT '是否需要支付流水号',
  `payNo` varchar(32)  DEFAULT NULL COMMENT '支付流水号',
  `created_date` datetime DEFAULT NULL,
  `updated_date` datetime DEFAULT NULL,
  `created_by` varchar(64) DEFAULT NULL,
  `updated_by` varchar(64) DEFAULT NULL,
  `version` bigint(20) DEFAULT NULL COMMENT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='主动还款进度查询入参表';

##主动还款进度查询返回表
CREATE TABLE `xyqb_initiative_repaysrate_resp` (
  `id` varchar(32)  NOT NULL COMMENT '主键',
  `sortNo` varchar(64) DEFAULT NULL COMMENT '请求标识位',
  `custNo` varchar(64) DEFAULT NULL COMMENT '客户编号',
  `repaySeq` varchar(32) DEFAULT NULL COMMENT '还款主键',
  `applSeq` varchar(16) DEFAULT NULL COMMENT '贷款申请流水号',
  `loanNo` varchar(64) DEFAULT NULL COMMENT '借据号',
  `serno` varchar(32)  DEFAULT NULL COMMENT '历史请求参数的serno',
  `coupKind` varchar(32)  DEFAULT NULL COMMENT '优惠券类型',
  `realPayAmt` varchar(32)  DEFAULT NULL COMMENT '应支付金额',
  `acCardNo` varchar(32)  DEFAULT NULL COMMENT '还款卡号',
  `setlMode` varchar(32)  DEFAULT NULL COMMENT '还款类型',
  `coupNo` varchar(32)  DEFAULT NULL COMMENT '优惠券号',
  `useCoup` varchar(32)  DEFAULT NULL COMMENT '是否使用优惠券',
  `coupUseAmt` varchar(32)  DEFAULT NULL COMMENT '优惠券减免金额',
  `loanTyp` varchar(32)  DEFAULT NULL COMMENT '贷款品种代码',
  `coupValue` varchar(32)  DEFAULT NULL COMMENT '优惠券面值',
  `psPerdNo` varchar(32)  DEFAULT NULL COMMENT '还款期号',
  `setlSts` varchar(32)  DEFAULT NULL COMMENT '还款状态',
  `tradeDt` varchar(32)  DEFAULT NULL COMMENT '交易日期',
  `mtdCde` varchar(32)  DEFAULT NULL COMMENT '贷款品种还款方式',
  `repayAmt` varchar(32)  DEFAULT NULL COMMENT '还款金额',
  `setlTyp` varchar(32)  DEFAULT NULL COMMENT '支付流水号',
  `failReason` varchar(32)  DEFAULT NULL COMMENT '还款失败原因',
  `typSeq` varchar(32)  DEFAULT NULL COMMENT '贷款品种流水号',
  `apprvTnr` varchar(32)  DEFAULT NULL COMMENT '总期数',
  `crtDt` varchar(32)  DEFAULT NULL COMMENT '创建（申请）时间',
  `payNo` varchar(32)  DEFAULT NULL COMMENT '支付流水号',
  `isNeedPayNo` varchar(32)  DEFAULT NULL COMMENT '是否需要支付流水号',
  `updDt` varchar(32)  DEFAULT NULL COMMENT '更新时间',
  `refFlag` varchar(32)  DEFAULT NULL COMMENT '映射后的错误码',
  `refMsg` varchar(32)  DEFAULT NULL COMMENT '映射后的错误原因',
  `created_date` datetime DEFAULT NULL,
  `updated_date` datetime DEFAULT NULL,
  `created_by` varchar(64) DEFAULT NULL,
  `updated_by` varchar(64) DEFAULT NULL,
  `version` bigint(20) DEFAULT NULL COMMENT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='主动还款进度查询返回表';

CREATE TABLE `xyqb_quota_info` (
  `id` bigint(10) NOT NULL AUTO_INCREMENT COMMENT 'id',
  `ser_no` varchar(36) DEFAULT  NULL COMMENT '流水号',
  `id_no` varchar(20) DEFAULT NULL COMMENT '身份证号码',
  `id_type` varchar(10) DEFAULT NULL COMMENT '身份证：20',
  `credit_type` varchar(10) DEFAULT NULL COMMENT '额度类型 通用额度：”01”专项额度：专项额度代码具体值',
  `created_by` varchar(50) NOT NULL COMMENT '创建人',
  `created_date` datetime NOT NULL COMMENT '创建时间',
  `updated_by` varchar(50) NOT NULL COMMENT '更新人',
  `updated_date` datetime NOT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `ser_no` (`ser_no`) USING BTREE,
  KEY `id_no` (`id_no`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='实时额度记录表';

create table `xyqb_quota_detail_info` (
  `id` bigint(10) not null auto_increment comment 'id',
  `ser_no` varchar(36) default  null comment '流水号',
  credit_typ varchar(36) default  null comment '额度类型 通用额度：”01”专项额度：专项额度代码',
  crd_amt  varchar(36) default  null comment '额度总金额 ',
  crd_com_amt  varchar(36) default  null comment '受托支付总额度 ',
  crd_com_used_amt  varchar(36) default  null comment '受托支付已支用额度金额',
  crd_com_avail_amt  varchar(36) default  null comment '受托支付可用额度金额',
  crd_nor_cmt  varchar(36) default  null comment '自主支付总额度',
  crd_nor_used_amt  varchar(36) default  null comment '自主支付已支用额度金额',
  crd_nor_avail_amt  varchar(36) default  null comment '自主支付可用额度金额',
  crd_sts  varchar(36) default  null comment '额度状态',
  cont_dt  varchar(36) default  null comment '额度有效期',
  cust_id  varchar(36) default  null comment '客户号',
  crd_no    varchar(36) default  null comment '额度协议号',     
  id_typ    varchar(36) default  null comment '证件类型',     
  cust_name     varchar(36) default  null comment '客户名称', 
  id_no     varchar(36) default  null comment '证件号码',     
  start_dt   varchar(36) default  null comment '开始日期',    
  end_dt      varchar(36) default  null comment '结束日期',   
  bch_cde    varchar(36) default  null comment '管理机构',    
  operator_cde   varchar(36) default  null comment '操作员代码',
  operator_name  varchar(36) default  null comment '操作员名称',
  operator_tel   varchar(36) default  null comment '操作联系电话',
  super_coopr  varchar(36) default  null comment '所属合作机构集团', 
  coopr_cde     varchar(36) default  null comment '合作机构代码', 
  coopr_name    varchar(36) default  null comment '合作机构名称', 
  coopr_zone    varchar(36) default  null comment '合作机构联系电话区号', 
  coopr_tel     varchar(36) default  null comment '合作机构联系电话', 
  coopr_sub     varchar(36) default  null comment '合作机构联系电话分机', 
  crt_usr     varchar(36) default  null comment '创建用户',   
  crt_bch    varchar(36) default  null comment '创建用户所在机构',   
  crt_bch_ind   varchar(36) default  null comment '创建用户是否为行内用户',  
  crt_dt      varchar(36) default  null comment '创建日期',   
  last_chg_dt    varchar(36) default  null comment '最后修改时间', 
  last_chg_usr   varchar(36) default  null comment '最后修改用户', 
  crd_seq     varchar(36) default  null comment '额度申请序列号',   
  spe_seq    varchar(36) default  null comment '专项额度类型流水号',    
  spe_typ     varchar(36) default  null comment '专项额度类型',   
  control_amt    varchar(36) default  null comment '额度当前受控金额',
  partner_label  varchar(36) default  null comment 'risklink机构标签',
  `created_by` varchar(50) not null comment '创建人',
  `created_date` datetime not null comment '创建时间',
  `updated_by` varchar(50) not null comment '更新人',
  `updated_date` datetime not null comment '更新时间',
  primary key (`id`),
  key `ser_no` (`ser_no`) using btree,
  key `id_no` (`id_no`) using btree
) engine=innodb auto_increment=1 default charset=utf8 comment='实时额度记录详情表';

CREATE TABLE `xyqb_decision_query_info` (
  `id` bigint(10) NOT NULL AUTO_INCREMENT COMMENT 'id',
  `name` varchar(50) DEFAULT NULL COMMENT '姓名',
  `phone` varchar(50) DEFAULT NULL COMMENT '客户注册手机号码',
  `id_number` varchar(50) DEFAULT NULL COMMENT '客户身份证号码',
  `status` varchar(10) DEFAULT NULL COMMENT '决策结果 Y-通过,N-拒绝',
  `zmf_score_min` varchar(10) DEFAULT NULL COMMENT '芝麻分最低分',
  `zmf_score_max` varchar(10) DEFAULT NULL COMMENT '芝麻分最高分',
  `ykg_score` varchar(10) DEFAULT NULL COMMENT '云科谷评分',
  `created_by` varchar(50) DEFAULT NULL COMMENT '创建人',
  `created_date` datetime DEFAULT NULL COMMENT '创建时间',
  `updated_by` varchar(50) DEFAULT NULL COMMENT '更新人',
  `updated_date` datetime DEFAULT NULL COMMENT '更新时间',
  `channel_code` varchar(64) DEFAULT NULL COMMENT '渠道号',
  PRIMARY KEY (`id`),
  KEY `id_number` (`id_number`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=64783 DEFAULT CHARSET=utf8 COMMENT='决策查询日志表';





























